do:
	cat Makefile

cp:
	cp ~/git/private-alice/c87/himono-plot/html/*.html .
	cp -r ~/git/private-alice/c87/himono-plot/html/img .
	cp ~/git/private-alice/c87/himono-plot/html/lib/pages.js ./lib/
	cp ~/git/private-alice/c87/himono-plot/html/lib/vnc.js ./lib/
